# Generated by Django 4.2.2 on 2023-06-27 18:42

import GameStats.Games.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', validators=[GameStats.Games.validators.image_size])),
                ('title', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2, message='game title must be at least 2 characters long!')])),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Sports', 'Sports'), ('Adventure', 'Adventure'), ('Role-play', 'Role-play'), ('Racing', 'Racing'), ('Other', 'Other')], max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('creator', models.CharField()),
            ],
        ),
    ]
