# Generated by Django 4.2.2 on 2023-06-29 05:26

import GameStats.Games.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[GameStats.Games.validators.image_size]),
        ),
    ]
