# Generated by Django 4.2.2 on 2023-06-30 07:40

import GameStats.Games.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(error_messages={'unique': 'A game already uses this image!'}, unique=True, upload_to='images', validators=[GameStats.Games.validators.image_size]),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(error_messages={'unique': 'Game with this name already exists!'}, max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='game title must be at least 2 characters long!')]),
        ),
    ]
