# Generated by Django 4.2.2 on 2023-06-30 07:47

import GameStats.Games.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_alter_game_image_alter_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='images', validators=[GameStats.Games.validators.image_size]),
        ),
    ]
